name: Daily Automated Backup to Backblaze B2

on:
  schedule:
    - cron: "*/2 * * * *" # runs every day at 00:00 UTC
  workflow_dispatch: # allows manual trigger in GitHub

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Install Postgres Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run Backup Script
        run: node backup.js backup
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}

          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          B2_BUCKET: ${{ secrets.B2_BUCKET }}
